### PR TITLE
Fix #1 and Add better Types

### LINKED ISSUE #1: [BUG🐛]: no support for `?inline`
Vite supports adding [`?inline`](https://vitejs.dev/guide/features.html#static-assets) to a file, to have it be inlined, however your plugin does not allow for such a modifier (<https://vitejs.dev/guide/features.html#static-assets>).

### PR DESCRIPTION
**Pull request by N0tExisting**
This Fixes #1, adds improved types & makes #5 redundant.

### CODE REVIEW

**Comment by N0tExisting** [comment]
This still needs some testing.

**Comment by jfgodoy** [comment]
thank you very much @N0tExisting for contributing :+1:. I'm going to check your PR

**Comment by N0tExisting** [comment]
@jfgodoy What do you think about adding a test project, that can be used to test this package?

**Comment by jfgodoy** [comment]
sorry @N0tExisting, I had to do a lot of changes to make ssr works. This PR now requires a lot of work to be up to date. The good news is that I have added support for "inline" param (or any other) in the main branch. 

I would love to see this PR split in three:
- support for "comp" (if you are still interested)
- types
- update documentation
- 
thank you very much for your time :+1:

**Comment by N0tExisting** [comment]
@jfgodoy Sorry for the late response I was working on a bunch of different stuff.
Will try to get this done on the weekend

Note that updating the documentation and types go hand in hand.

**Pull request closed without merging**
